mutation AddTransaction (
  $user_id: String!,
  $description: String!,
  $vendor_id: String!,
  $category: String!,
  $debit: Boolean!,
  $credit: Boolean!,
  $amount: Float!
) {
  addTransaction (
    user_id: $user_id,
    description: $description,
    vendor_id: $vendor_id,
    category: $category,
    debit: $debit,
    credit: $credit,
    amount: $amount,
  ) {
    id
  }
}